DUTYCYCLE_FR:        int = 18
MOTOR_FRONT_RIGHT_A: int = 24
MOTOR_FRONT_RIGHT_B: int = 23

DUTYCYCLE_FL:       int = 17
MOTOR_FRONT_LEFT_A: int = 27
MOTOR_FRONT_LEFT_B: int = 22

DUTYCYCLE_BR:       int = 16
MOTOR_BACK_RIGHT_A: int = 20
MOTOR_BACK_RIGHT_B: int = 21

DUTYCYCLE_BL:      int = 13
MOTOR_BACK_LEFT_A: int = 19
MOTOR_BACK_LEFT_B: int = 26