DUTYCYCLE_FR: int = 18
DUTYCYCLE_FL: int = 12
DUTYCYCLE_BR: int = 13
DUTYCYCLE_BL: int = 19

MOTOR_FRONT_RIGHT_A: int = 24
MOTOR_FRONT_RIGHT_B: int = 23
MOTOR_FRONT_LEFT_A: int  =  8
MOTOR_FRONT_LEFT_B: int  = 25

MOTOR_BACK_RIGHT_A: int = 27
MOTOR_BACK_RIGHT_B: int = 22
MOTOR_BACK_LEFT_A: int  =  6
MOTOR_BACK_LEFT_B: int  =  5